[versions]
shadow = "9.2.2"

guava = "33.5.0-jre"
gson = "2.13.2"
asm = "9.9"
jspecify = "1.0.0"
jopt = "6.0-alpha-3"
flatlaf = "3.4"
syntaxpain = "internal"
swing_dpi = "0.10"
fontchooser = "2.5.2"
tinylog = "2.7.0"
quilt_config = "1.3.2"
javaparser = "3.27.0"
jflex = "1.9.1"

vineflower = "1.11.1"
cfr = "0.2.2"
procyon = "0.6.0"

junit = "6.0.1"
hamcrest = "3.0"
jimfs = "1.3.1"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm_commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm_tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm_util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }

jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

tinylog_api = { module = "org.tinylog:tinylog-api", version.ref = "tinylog" }
tinylog_impl = { module = "org.tinylog:tinylog-impl", version.ref = "tinylog" }

quilt_config = { module = "org.quiltmc:quilt-config", version.ref = "quilt_config" }
quilt_config_toml = { module = "org.quiltmc.quilt-config.serializers:toml", version.ref = "quilt_config" }

jopt = { module = "net.sf.jopt-simple:jopt-simple", version.ref = "jopt" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
flatlaf_extras = { module = "com.formdev:flatlaf-extras", version.ref = "flatlaf" }
syntaxpain = { module = "org.quiltmc:syntaxpain", version.ref = "syntaxpain" }
swing_dpi = { module = "com.github.lukeu:swing-dpi", version.ref = "swing_dpi" }
fontchooser = { module = "org.drjekyll:fontchooser", version.ref = "fontchooser" }
javaparser = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }
jflex = { module = "de.jflex:jflex", version.ref = "jflex" }

vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
cfr = { module = "net.fabricmc:cfr", version.ref = "cfr" }
procyon = { module = "org.bitbucket.mstrobel:procyon-compilertools", version.ref = "procyon" }

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit_launcher = { module = "org.junit.platform:junit-platform-launcher" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }

[bundles]
asm = ["asm", "asm_commons", "asm_tree", "asm_util"]
tinylog = ["tinylog_api", "tinylog_impl"]
quilt_config = ["quilt_config", "quilt_config_toml"]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
