[versions]
shadow = "8.1.1"

guava = "32.0.1-jre"
gson = "2.10.1"
asm = "9.4"
jopt = "6.0-alpha-3"
flatlaf = "3.1.1"
syntaxpane = "1.2.1"
swing_dpi = "0.10"
fontchooser = "2.5.2"
tinylog = "2.6.2"

quiltflower = "1.10.0-20230513.181048-90"
cfr = "0.2.1"
procyon = "0.6.0"

proguard = "7.3.2"
junit = "5.9.3"
hamcrest = "2.2"
jimfs = "1.2"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm_commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm_tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm_util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }

tinylog_api = { module = "org.tinylog:tinylog-api", version.ref = "tinylog" }
tinylog_impl = { module = "org.tinylog:tinylog-impl", version.ref = "tinylog" }

jopt = { module = "net.sf.jopt-simple:jopt-simple", version.ref = "jopt" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
flatlaf_extras = { module = "com.formdev:flatlaf-extras", version.ref = "flatlaf" }
syntaxpane = { module = "de.sciss:syntaxpane", version.ref = "syntaxpane" }
swing_dpi = { module = "com.github.lukeu:swing-dpi", version.ref = "swing_dpi" }
fontchooser = { module = "org.drjekyll:fontchooser", version.ref = "fontchooser" }

quiltflower = { module = "org.quiltmc:quiltflower", version.ref = "quiltflower" }
cfr = { module = "net.fabricmc:cfr", version.ref = "cfr" }
procyon = { module = "org.bitbucket.mstrobel:procyon-compilertools", version.ref = "procyon" }

proguard = { module = "com.guardsquare:proguard-base", version.ref = "proguard" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }

[bundles]
asm = ["asm", "asm_commons", "asm_tree", "asm_util"]
tinylog = ["tinylog_api", "tinylog_impl"]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
